id = "one-dark-pro-yesh"
name = "One Dark Pro (Yesh Version)"
version = "0.0.1"
schema_version = 1
authors = ["yesh"]
description = "A port of VSCode One Dark Pro with some tweaks"
repository = "https://github.com/yesh-dispatch24/zed-one-dark-proo"
